# Generated by Django 3.2.16 on 2022-10-19 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock',
            new_name='Product',
        ),
    ]
