# Generated by Django 3.2.16 on 2022-11-08 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_product_has_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
    ]
